version: 0.2

env:
  shell: bash
  variables:
    TEST: "Hello Test Variable"
  exported-variables:
    - TEST
    - STACK_NAME
    - WEB_BUCKET

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - npm install -g aws-cdk
      - npm install -g typescript
      - cdk --version

  build:
    commands:
      - echo Build CDK project...
      - cd app/aws
      - npm install
      - export STACK_NAME=$(tr '/' '' <<<"learningtracker${CODEBUILD_SOURCE_VERSION}") && cdk deploy --require-approval never --outputs-file outputs.json
      - cat outputs.json
      - echo .${STACK_NAME}.WEBBUCKET
      - echo $(jq .${STACK_NAME}.WEBBUCKET outputs.json)
      - aws s3 sync $(jq .${STACK_NAME}.WEBBUCKET outputs.json) ./web/build
      - echo Deploy completed on the `date`